version: "3.9"

networks:
  ren-network:
    name: ren-network
    driver: bridge

services:
  ren:
    build:
      context: .
    container_name: ren
    restart: unless-stopped
    networks:
      - ren-network
    volumes:
      - type: bind
        source: ./data/ren/data
        target: /data
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX:-.}
      - TZ=${TIMEZONE:-America/Vancouver}
      - PUID=1000
