version: "3.9"

networks:
  ren-network:
    name: ren-network
    driver: bridge

services:
  ren:
    build:
      context: .
    container_name: ren
    restart: unless-stopped
    networks:
      - ren-network
    volumes:
      - ren-data:/data
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX}
      - TZ=${TIMEZONE:-America/Vancouver}
      - PUID=1000
      - CUSTOM_REDBOT_PACKAGE=git+https://github.com/SFUAnime/Ren.git@V3/testing
      - EXTRA_ARGS=${EXTRA_ARGS}
